project:
  type: website
  output-dir: docs

website:
  title: "Ryan Dobson"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - href: research.qmd
        text: Research
      - href: cv.qmd
        text: CV

format:
  html:
    theme: cosmo
    toc: true