project:
  type: website
  output-dir: docs

website:
  title: "Ryan Dobson"
  navbar:
    left:
      - href: index.qmd
      - href: research.qmd
      - href: code.qmd
      - href: cv.qmd

  page-footer:
    background: light
    left: "© 2026 Ryan Dobson"
    right:
      - icon: github
        href: https://github.com/ryandobson
      - icon: envelope
        href: mailto:rdobson@unm.edu

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true